site_name: my-package-mloukeris

repo_url: https://github.com/donMichaelL/my-package
repo_name: donMichaelL/my-package

theme:
  name: material
  palette:
    primary: green
  font:
    text: Roboto
  icon:
    repo: fontawesome/brands/github

plugins:
  - search
  - include-markdown
  - macros
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google

markdown_extensions:
  - mkdocs-click

nav:
  - Home: index.md
  - CLI Reference: cli.md
  - API Reference: api.md
